

package com.training.sanity.tests;

import static org.testng.Assert.assertEquals;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import com.training.generics.ScreenShot;
import com.training.pom.ResetPasswordPOM;
import com.training.utility.DriverFactory;
import com.training.utility.DriverNames;

public class RETC_003_ResetPassword{

	private WebDriver driver;
	private WebDriverWait wait;
	private String baseUrl;
	private static Properties properties;
	private ScreenShot screenShot;
	private ResetPasswordPOM resetPasswordPOM;

	@BeforeClass
		  
		  public void beforeClass() throws IOException 
	 {
				properties = new Properties();
				FileInputStream inStream = new FileInputStream("./resources/others.properties");
				properties.load(inStream);
	  }

	@BeforeMethod
		  public void beforeMethod() 
		  {
			  
			  driver = DriverFactory.getDriver(DriverNames.CHROME);
				resetPasswordPOM = new ResetPasswordPOM(driver);
				baseUrl = properties.getProperty("baseURL");
				screenShot = new ScreenShot(driver);
				// open the browser
				driver.get(baseUrl);
		  }

	@Test 
	public void validRETC_003_ResetPassword() throws InterruptedException {
		
		wait = new WebDriverWait(driver, 60); // this function will be wait 180 secs to load the page
		wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getLoginRegister())); // launch the Application
		screenShot.captureScreenShot("RETC_003_ResetPasswrod_00_launch"); 
		
		resetPasswordPOM.clicklogin_register();	 // click on login/register link
		wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getForgotPassword())); // Wait until Forgot password text displays
		screenShot.captureScreenShot("RETC_003_ResetPasswrod_001_Login_Register");
		
		resetPasswordPOM.clickforgotPassword(); //click on forgot Password
		wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getEmail())); // Wait until reset password text displays
		screenShot.captureScreenShot("RETC_003_ResetPasswrod_02_Lost_Password");
		
		resetPasswordPOM.sendemail("rameshaku2019@gmail.com"); //Enter Mail id 
		
		resetPasswordPOM.clickresetpwd(); // Click on Reset password button
		wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getConflink()));
		screenShot.captureScreenShot("RETC_003_ResetPasswrod_03_Confirmation_Status");
		
		// The below function will be switch to another tab and open Gmail application
		 ArrayList<String> tabs = new ArrayList<String> (driver.getWindowHandles());
		 driver.switchTo().window(tabs.get(0));
		 driver.get("http://www.gmail.com");
		 
		 wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getGmailID())); // Wait until gmail id text displays 
		 screenShot.captureScreenShot("RETC_003_ResetPasswrod_04_Gmaillaunch");	
		 
		 resetPasswordPOM.sendGmailID("rameshaku2019@gmail.com"); //Enter gmail id
		 
		 resetPasswordPOM.clickGmailNext();	 // click on next button
		 
		 wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getGmailpassword())); // Enter password 
		 
		 screenShot.captureScreenShot("RETC_003_ResetPasswrod_05_gmailnext"); 
		 
		 resetPasswordPOM.sendGmailPassword("winter@1234"); // Click on password
		 
		 resetPasswordPOM.clickGmailPasswordNext();	 // click on next button
		 wait.until(ExpectedConditions.invisibilityOf(resetPasswordPOM.getGmailWordPress()));
		 screenShot.captureScreenShot("RETC_003_ResetPasswrod_06_gmailsign");
			 
		 resetPasswordPOM.clickGmailWordPress(); // Click on mail which was generated by Real Estate 
		 
		 Thread.sleep(5000);
		 
		// wait.until(ExpectedConditions.invisibilityOf(resetPasswordPOM.getWordPressLink()));
		 screenShot.captureScreenShot("RETC_003_ResetPasswrod_07_gmailmailopen");
			 
		resetPasswordPOM.clickWordPressLink();	 //Click on Reset password Link
		 
		 // The below function will be switch to another tab and open Reset password URL 
		 
		 
		 ArrayList<String> tabs1 = new ArrayList<String> (driver.getWindowHandles());
		 driver.switchTo().window(tabs1.get(1));

		 
		 wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getEnterpassword())); // Wait until New password text displays
		 
		 screenShot.captureScreenShot("RETC_003_ResetPasswrod_08_ResetPassword");
		
		
		 		 	 
		 resetPasswordPOM.sendEnterpassword("winter@1234"); // Enter new password and Re enter password
		 
		 resetPasswordPOM.sendReEnterpassword("winter@1234");
		 
		 resetPasswordPOM.clickResetpassbutton();	 // Click on Reset Password button
		 
		 wait.until(ExpectedConditions.visibilityOf(resetPasswordPOM.getpasswordchanged()));
		 screenShot.captureScreenShot("RETC_003_ResetPasswrod_09_PasswordChanged");
		 
			
			String updateprofile = driver.findElement(By.id("post-124")).getText();
			
		
				//Password has been changed. Message should get displayed


			  String Expected ="Password has been changed.";
			  String Actual =  updateprofile;		
			  assertEquals(Actual, Expected);
				 	 
  }
	


	
	@AfterMethod
  
	  public void tearDown() throws Exception
  			{
			Thread.sleep(5000);
			driver.quit();
	  
  			}
	

}



